sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: zbGW9CmcJzyhStiP8qPkEHgDHUdadT
    access-key-id: LTAI5tAnHr2JrG7xBVLZHZjx
    bucket-name: hl0yang-sky
