sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: 
    access-key-secret: 
    access-key-id: 
    bucket-name: 
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx0d5120c89e421bf9
    secret: 2c655865610b83120cbdcced0cc59db5

